services:
  db:
    image: postgres:16
    container_name: ggtowndb-container
    environment:
      POSTGRES_USER: kamivision
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ggtown_db
    ports:
      - "5433:5432"
    volumes:
      - ggtown_postgres_data:/var/lib/postgresql/data

  backend:
    build: ./server
    container_name: ggtownserver-container
    command: sh -c "python manage.py migrate && gunicorn town_proj.wsgi --bind 0.0.0:8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    depends_on:
      - db

  frontend:
    build: ./client
    container_name: ggtownclient-container
    ports:
      - "80:80"
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  ggtown_postgres_data: