# Generated by Django 6.0.3 on 2026-03-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Townie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='townie', max_length=255)),
                ('quest_type', models.CharField(default='other', max_length=255)),
                ('quest', models.CharField(default='unknown', max_length=255)),
                ('quest_amount', models.CharField(default='1', max_length=255)),
            ],
        ),
    ]
