# Generated by Django 6.0.3 on 2026-03-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='townie',
            name='original_quest',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
