# Generated by Django 6.0.3 on 2026-03-31 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('townie_app', '0002_townie_original_quest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_amount', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('townie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='townie_app.townie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['townie__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='questprogress',
            constraint=models.UniqueConstraint(fields=('user', 'townie'), name='unique_user_townie_progress'),
        ),
    ]