# Generated by Django 6.0.3 on 2026-04-04 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_questprogress_is_pinned'),
        ('townie_app', '0002_townie_original_quest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TowniePin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('townie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by_users', to='townie_app.townie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='townie_pins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['townie__name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'townie'), name='unique_user_townie_pin')],
            },
        ),
    ]
